### ISSUE TITLE
Any know plugin conflicts? Plugin suddenly stopped working...

### ISSUE THREAD

**Issue by adaptifyDesigns** [anttiviljami/wp-pdf-templates#5]
Hi, 

I was using your plugin effectively for the last 3 months, but suddenly (yesterday?) whenever I try to generate a pdf via the url endpoint I get a 502 server response because it times out.

Are there any known plugin conflicts. The site I'm using this on is in active development so there have been many plugins installed and tested over the last week alone. 

The problem is that I have not seen anything in my error logs regarding the pdf plugin, so I have no clue as to what's going on.

I know it's a long shot, but I just thought I'd ask if you have heard of any plugin conflicts out there?

Thanks in advance,
- Colin

**Comment by adaptifyDesigns** [comment]
**UPDATE**
I just found the culprit. 

FYI, it's a plugin called [Awesome Support - Wordpress Support Plugin](https://wordpress.org/plugins/awesome-support/)

I'll be contacting their support asap. 

I doubt it, but have you ever heard about this conflict before? I have no clue where to start with regard to troubleshooting the issue, as there are no errors being logged, just a server time out and a 502 response.

Any nudges in the right direction would be extremely helpful.

Thanks!

**Comment by onnimonni** [comment]
Thanks for reporting about this.

And well there's no silver bullet for fixing this. Usually If we don't see anything useful in the logs we use local copy of the site in our [vagrant box](https://github.com/seravo/wordpress) and use [xdebug](http://xdebug.org) to crawl through the request to see whats going on.

Or then you can comment out stuff from awesome support plugin until you can find the exact location where the problem lies.

I hope this helps

**Comment by adaptifyDesigns** [comment]
Thanks for the suggestions :-)
